### ISSUE TITLE
Cannot read tolowercase of undefined

### ISSUE THREAD

**Issue by psychonetic** [achwilko/vue-material-icon#1]
The example provided in the readme does not work.
```
import VueMaterialIcon from 'vue-material-icon'
Vue.component(VueMaterialIcon.favorite, VueMaterialIcon)
```

Cannot read property 'toLowerCase' of undefined.

Any idea?

**Comment by achwilko** [comment]
Hi @psychonetic 

Thanks for using the package. I've fixed the issue by adding missing component's name.

By the way, you should use it as below (name instead of favorite):
```
// in your main.js
import VueMaterialIcon from 'vue-material-icon'
Vue.component(VueMaterialIcon.name, VueMaterialIcon)

<!-- in your HTML template -->
<vue-material-icon name="favorite" :size="32"></vue-material-icon>
```

Let me know if it's OK now.

**Comment by psychonetic** [comment]
@achwilko 

To clarify: 
I tried both 
`Vue.component(VueMaterialIcon.name, VueMaterialIcon)`
and also 
`Vue.component(VueMaterialIcon.favorite, VueMaterialIcon),`
 but for both I got the same error as mentioned above.

Anyway, after your update it is now working like a charme!
Thank you!
