### ISSUE TITLE
Update package version

### ISSUE THREAD

**Issue by LeCoupa** [achwilko/vue-material-icon#6]
Also, when you are doing changes to your package, don't forget to update your `package.json` version number. You can follow the [semantic versioning](https://semver.org/) if it can help. :-)

```javascript
{
  "version": "1.0.0",  // <-- update this number to 1.0.1 etc.
}
```

**Comment by achwilko** [comment]
Hi @LeCoupa 

Sure, will be doing that because of NPM requirements to publish:
https://docs.npmjs.com/cli/version

I will update whole package as soon as I will get some free time, stay tuned.
